version: '3.8'

services:
  web:
    container_name: django_container
    build:
      context: .
      dockerfile: backend/Dockerfile
    restart: always
    command: sh -c "cd backend && 
                    gunicorn test_django_stripe.wsgi:application --bind 0.0.0.0:8000"

    env_file:
      - ./.env.prod
    volumes:
      - static_volume:/home/app/web/backend/static/
    expose:
      - 8000
    depends_on:
      - db

  stripe:
    container_name: stripe_container
    image: stripe/stripe-cli:v1.13.9
    command: listen --forward-to 127.0.0.1:1337/webhooks/stripe/
    env_file:
      - ./.env.stripe_cli
    depends_on:
      - web

  db:
    container_name: postgres_container
    image: postgres:15.1-alpine
    restart: always
    env_file:
      - ./.env.prod.db
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  nginx:
    container_name: nginx_container
    restart: always
    build: ./nginx
    ports:
      - "1337:80"
    volumes:
      - static_volume:/home/app/web/backend/static/
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
