# Generated by Django 4.1.7 on 2023-02-20 09:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_options_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=150, verbose_name='Tax type')),
                ('inclusive', models.BooleanField(default=False, verbose_name='Tax is added to the amount')),
                ('percentage', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Tax percentage')),
                ('country', models.CharField(max_length=2, verbose_name='Valid two-letter ISO country code')),
                ('state', models.CharField(blank=True, max_length=2, null=True, verbose_name='Valid two-letter ISO state code (for USA)')),
            ],
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'Item', 'verbose_name_plural': 'Items'},
        ),
    ]
