# Generated by Django 4.1.7 on 2023-02-20 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_tax_alter_item_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tax',
            options={'verbose_name': 'Tax', 'verbose_name_plural': 'Taxes'},
        ),
        migrations.AddField(
            model_name='order',
            name='tax',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='orders.tax', verbose_name='Tax'),
        ),
        migrations.AlterField(
            model_name='tax',
            name='inclusive',
            field=models.BooleanField(default=True, verbose_name='Tax is included in the order amount'),
        ),
    ]
