# Generated by Django 4.1.7 on 2023-02-20 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_discount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discount',
            options={'verbose_name': 'Tax', 'verbose_name_plural': 'Taxes'},
        ),
        migrations.AddField(
            model_name='discount',
            name='name',
            field=models.CharField(default=1, max_length=100, verbose_name='Name'),
            preserve_default=False,
        ),
    ]
